services:
  app:
    image: thewh1teagle/speedlens
    restart: unless-stopped
    command: /lens /data/config.json
    volumes:
      - ./data:/data
    ports:
      - 8080:8080
    environment:
      - LENS_HOST=0.0.0.0
      - LENS_PORT=8080
